appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: gJWLX2Y6qKOBydLQsE2cftWvxY2ZwKM1IeuJjSOl8UHZX+zYf0M8KGNovTn6Nxfw5ZemDqvRNuYPRDiYzvOM1JAgkCYBy15II4l5sGHr2K7y3YXaV0hCJFhH+BthLnaRkhUnyy68YmWWfYapIbMEkLg21SCyB3VboTSiHQ+m+c67y7LN3iKv1wFgPttAEphd55iCywbKoTXsP4OqoW8uAa/LP9R88VCNwIONobk4m/yl3lJRw1tBQO9jlSZeT4clb030Vw55HQUfCYnbh0s5xqUkWLD9KtAg60wa7WeDFURgACDRKVYsiZI3dQueZJf9BRl/uRGkQaA9vlCa6jk16iAyhQ9oXR6eBqTCq8ijU1PtvWtRqYtDrPjCP+2erEGPy4B7WwSS///b4I7eR4xf5k9G4vYp1TWk2+2fJX6o0vhQk0QyND2MUzUiGB+qkdJ+hh0Luu/vTmoH0d4X9wHpKNw6lwLGUYhMIVeFZCdI/Sbn4Z2xU8XYtwhf+dFZ6dOpYZbI+xcYSEpEDoP6wQAEW7R/SWDWngSkYINSrXTEqoS1roznZkRbTtOD2prJNxp2Sx9K/nRXdOhXZrr+RhO8ueBYyzasOo1RNprqeAuMzWf2G9nAupJYfw3gM1Bginrs5w77TO78tfzAPbNQJRuL/Wbcap+lx3QA6/a63KEDY2s=}
